name: Generate snake animation

on:
  schedule:
    - cron: '*/12 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # --- PASO AÑADIDO AQUÍ ---
      # Este paso clona tu repositorio para que los siguientes pasos puedan acceder a él
      - name: Checkout repository
        uses: actions/checkout@v4 # Puedes usar @v3 o @v4, v4 es más reciente

      # Paso para generar el archivo SVG de la serpiente
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg?palette=github-dark

      # Paso para hacer commit y push del archivo SVG generado
      - name: Commit and push snake animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'docs: update snake animation'
          add: 'dist/github-snake.svg'
          push: true
