name: Generate snake animation

on:
  # Se ejecuta cada 12 horas
  schedule:
    - cron: '*/12 * * * *'
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  # Opcional: también se ejecuta en cada push a la rama main
  # Si no quieres esto, puedes eliminar las siguientes 3 líneas:
  push:
    branches:
      - main

jobs:
  generate:
    # Permisos necesarios para que la acción pueda escribir en el repositorio (hacer commit)
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5 # Tiempo máximo de ejecución del job

    steps:
      # Primer paso: Genera el archivo SVG de la serpiente
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          # Nombre de usuario de GitHub (se toma automáticamente del repositorio)
          github_user_name: ${{ github.repository_owner }}
          # Archivo de salida: se guardará como github-snake.svg en una carpeta llamada 'dist'
          # Con la paleta de colores 'github-dark'
          outputs: dist/github-snake.svg?palette=github-dark

      # Segundo paso: Hace commit y push del archivo SVG generado a tu rama principal
      - name: Commit and push snake animation
        uses: EndBug/add-and-commit@v9
        with:
          # Nombre del autor del commit (será el bot de GitHub Actions)
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          # Mensaje del commit
          message: 'docs: update snake animation'
          # Archivo(s) a añadir al commit (el que se generó en el paso anterior)
          add: 'dist/github-snake.svg'
          # Hace push directamente a la rama donde se está ejecutando el workflow (main en este caso)
          push: true
          # Opcional: Si tu rama principal tuviera un nombre diferente a 'main', 
          # lo especificarías aquí, por ejemplo: branch: master
